dispatcher.py:303 #ERROR    [2023-10-28 22:35:42,255] - aiogram.event - Cause exception while process update id=482584117 by bot id=6004120980
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/calendar_handlers.py", line 276, in process_get_statistic
    query: list = take_addresses_objects(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/db/crud.py", line 182, in take_addresses_objects
    .filter(Days.users_id == user.id)
                             ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
dispatcher.py:303 #ERROR    [2023-12-02 16:01:47,548] - aiogram.event - Cause exception while process update id=482584141 by bot id=6004120980
ValidationError: 1 validation error for InlineKeyboardButton
text
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/edit_user_data_handlers.py", line 26, in process_edit_user_data
    reply_markup=user_data_keyboard(message.from_user.id),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/keyboards/user_data_keyboard.py", line 41, in user_data_keyboard
    score_price: InlineKeyboardButton = InlineKeyboardButton(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for InlineKeyboardButton
text
  none is not an allowed value (type=type_error.none.not_allowed)
dispatcher.py:303 #ERROR    [2023-12-02 16:11:36,487] - aiogram.event - Cause exception while process update id=482584143 by bot id=6004120980
KeyError: 'score_price'
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/edit_user_data_handlers.py", line 40, in process_edit_user_field
    text=LEXICON_EDIT_USER[callback_data.field_name],
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'score_price'
dispatcher.py:303 #ERROR    [2023-12-02 16:18:50,211] - aiogram.event - Cause exception while process update id=482584148 by bot id=6004120980
TypeError: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/edit_user_data_handlers.py", line 26, in process_edit_user_data
    reply_markup=user_data_keyboard(message.from_user.id),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/keyboards/user_data_keyboard.py", line 42, in user_data_keyboard
    text="Стоимость балла " + user.score_price + " руб.",
         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
dispatcher.py:303 #ERROR    [2023-12-02 16:20:54,133] - aiogram.event - Cause exception while process update id=482584158 by bot id=6004120980
DataError: (psycopg.errors.InvalidTextRepresentation) invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'
[SQL: UPDATE users SET updated_on=%(updated_on)s::TIMESTAMP WITHOUT TIME ZONE, score_price=%(score_price)s::INTEGER WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'updated_on': datetime.datetime(2023, 12, 2, 16, 20, 54, 130727), 'score_price': 'F', 'users_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.InvalidTextRepresentation: invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/edit_user_data_handlers.py", line 49, in process_update_user_field
    await edit_user_field(message.from_user.id, users_field["field_name"], message.text)
  File "/home/gigaden/PycharmProjects/installators_shcedule/db/crud.py", line 198, in edit_user_field
    session.commit()
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 553, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1906, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1221, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1196, in _prepare_impl
    self.session.flush()
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4154, in flush
    self._flush(objects)
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4290, in _flush
    with util.safe_reraise():
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4251, in _flush
    flush_context.execute()
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 904, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
           ^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.DataError: (psycopg.errors.InvalidTextRepresentation) invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'
[SQL: UPDATE users SET updated_on=%(updated_on)s::TIMESTAMP WITHOUT TIME ZONE, score_price=%(score_price)s::INTEGER WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'updated_on': datetime.datetime(2023, 12, 2, 16, 20, 54, 130727), 'score_price': 'F', 'users_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
dispatcher.py:303 #ERROR    [2023-12-02 16:20:59,362] - aiogram.event - Cause exception while process update id=482584159 by bot id=6004120980
PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg.errors.InvalidTextRepresentation) invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'
[SQL: UPDATE users SET updated_on=%(updated_on)s::TIMESTAMP WITHOUT TIME ZONE, score_price=%(score_price)s::INTEGER WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'updated_on': datetime.datetime(2023, 12, 2, 16, 20, 54, 130727), 'score_price': 'F', 'users_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/edit_user_data_handlers.py", line 65, in process_cancel_edit_field
    reply_markup=user_data_keyboard(callback.from_user.id),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/keyboards/user_data_keyboard.py", line 16, in user_data_keyboard
    user: models.Users = get_user(tg_id)
                         ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/db/crud.py", line 39, in get_user
    return session.query(Users).filter(Users.tg_id == tg_id).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2747, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2117, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1984, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 906, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg.errors.InvalidTextRepresentation) invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'
[SQL: UPDATE users SET updated_on=%(updated_on)s::TIMESTAMP WITHOUT TIME ZONE, score_price=%(score_price)s::INTEGER WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'updated_on': datetime.datetime(2023, 12, 2, 16, 20, 54, 130727), 'score_price': 'F', 'users_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
dispatcher.py:303 #ERROR    [2023-12-02 16:21:03,149] - aiogram.event - Cause exception while process update id=482584160 by bot id=6004120980
PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg.errors.InvalidTextRepresentation) invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'
[SQL: UPDATE users SET updated_on=%(updated_on)s::TIMESTAMP WITHOUT TIME ZONE, score_price=%(score_price)s::INTEGER WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'updated_on': datetime.datetime(2023, 12, 2, 16, 20, 54, 130727), 'score_price': 'F', 'users_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/edit_user_data_handlers.py", line 23, in process_edit_user_data
    if await check_user_in_db(message.from_user.id):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/db/crud.py", line 14, in check_user_in_db
    if session.query(Users).filter(Users.tg_id == tg_id).first():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2747, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2117, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1984, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 906, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg.errors.InvalidTextRepresentation) invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'
[SQL: UPDATE users SET updated_on=%(updated_on)s::TIMESTAMP WITHOUT TIME ZONE, score_price=%(score_price)s::INTEGER WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'updated_on': datetime.datetime(2023, 12, 2, 16, 20, 54, 130727), 'score_price': 'F', 'users_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
dispatcher.py:303 #ERROR    [2023-12-02 16:21:21,119] - aiogram.event - Cause exception while process update id=482584161 by bot id=6004120980
PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg.errors.InvalidTextRepresentation) invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'
[SQL: UPDATE users SET updated_on=%(updated_on)s::TIMESTAMP WITHOUT TIME ZONE, score_price=%(score_price)s::INTEGER WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'updated_on': datetime.datetime(2023, 12, 2, 16, 20, 54, 130727), 'score_price': 'F', 'users_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/edit_user_data_handlers.py", line 23, in process_edit_user_data
    if await check_user_in_db(message.from_user.id):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/db/crud.py", line 14, in check_user_in_db
    if session.query(Users).filter(Users.tg_id == tg_id).first():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2747, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2117, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1984, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 906, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg.errors.InvalidTextRepresentation) invalid input syntax for type integer: "F"
CONTEXT:  unnamed portal parameter $2 = '...'
[SQL: UPDATE users SET updated_on=%(updated_on)s::TIMESTAMP WITHOUT TIME ZONE, score_price=%(score_price)s::INTEGER WHERE users.id = %(users_id)s::INTEGER]
[parameters: {'updated_on': datetime.datetime(2023, 12, 2, 16, 20, 54, 130727), 'score_price': 'F', 'users_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)
dispatcher.py:303 #ERROR    [2023-12-04 11:23:43,936] - aiogram.event - Cause exception while process update id=482584201 by bot id=6004120980
AttributeError: 'list' object has no attribute 'year'
Traceback (most recent call last):
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 297, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 146, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 264, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 123, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/gigaden/PycharmProjects/installators_shcedule/handlers/add_scores_handlers.py", line 71, in process_add_scores
    year, month, day = user_date["curent_date"].year, user_date["curent_date"].month, user_date["curent_date"].day
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'year'
